### ISSUE TITLE
Redis out brings the entire site down

### ISSUE THREAD

**Issue by dblock** [artsy/force#1089]
https://artsy.slack.com/archives/C02CAB1KW/p1490284015357384

```
2017-03-23T15:46:43.674986+00:00 app[web.4]: REDIS_CONNECTION_ERROR { ReplyError: ERR max number of clients reached
2017-03-23T15:46:43.675002+00:00 app[web.4]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:181:12)
2017-03-23T15:46:43.675003+00:00 app[web.4]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:291:14)
2017-03-23T15:46:43.675004+00:00 app[web.4]: 
2017-03-23T15:46:43.675005+00:00 app[web.4]:   command: 'AUTH',
2017-03-23T15:46:43.675006+00:00 app[web.4]:   args: [ '' ],
2017-03-23T15:46:43.675007+00:00 app[web.4]:   code: 'ERR' }
```

```
2017-03-23T15:46:40.932096+00:00 app[web.1]: REDIS_CONNECTION_ERROR { Error: Redis connection to dab.redistogo.com:9305 failed - write EPIPE
2017-03-23T15:46:40.932127+00:00 app[web.1]:     at exports._errnoException (util.js:1018:11)
2017-03-23T15:46:40.932128+00:00 app[web.1]:     at WriteWrap.afterWrite (net.js:804:14)
2017-03-23T15:46:40.932129+00:00 app[web.1]:  code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by dblock** [comment]
This may have been a red herring, https://github.com/artsy/force/blob/a30de83ac07aaeee15a339c0d9c005968fab77d7/lib/cache.coffee#L21
