### ISSUE TITLE
Gene pages that display by artist look broken/funky

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#1457]
Re: https://artsy.slack.com/archives/C0GNAB0US/p1495471320836075

https://www.artsy.net/gene/contemporary-chinese-art - display by artist, broken
https://www.artsy.net/gene/painting - display by artworks, is working

**Comment by mzikherman** [comment]
Looks like the API call to return artists for a gene, e.g- https://api.artsy.net/api/v1/gene/contemporary-chinese-art/artists are returning no results.

Further investigating in the console and NewRelic:

<img width="1049" alt="screen shot 2017-05-22 at 1 09 06 pm" src="https://cloud.githubusercontent.com/assets/1457859/26320176/e2254c44-3eef-11e7-8cca-e67081d7488a.png">

and

```
gravity:production> ArtistGeneValueIndex.latest.documents.first
Mongo::Error::OperationFailure: not authorized for query on gravity-imports.base_imported_indices.snapshot-3937 (13)
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/operation/result.rb:256:in `validate!'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/operation/executable.rb:37:in `block in execute'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/server/connection_pool.rb:107:in `with_connection'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/server.rb:242:in `with_connection'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/operation/executable.rb:35:in `execute'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:81:in `send_initial_query'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:41:in `block in each'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:51:in `call'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:51:in `read_with_retry'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:39:in `each'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/query_cache.rb:222:in `each'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:248:in `first'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:248:in `block in first'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:513:in `try_cache'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:246:in `first'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gems/mongoid-6.0.3/lib/mongoid/contextual.rb:20:in `first'
	from /home/deploy/.bundler/gravity/ruby/2.2.0/gem
```
