### ISSUE TITLE
Button in email confirmation banner renders in front of nav menus

### ISSUE THREAD

**Issue by olerichter00** [artsy/force#6824]
## Problem

The "Send email" button in the`EmailConfirmationCTA` flash banner is rendered in front of the `NavItemPanel` menu and therefore visible and clickable when the menu is open.

![Uploading Screen Shot 2020-12-17 at 12.37.53.png…]()

## Steps to reproduce

- Create a new account or log in with an unconfirmed account
- Wait until the email confirmation cta appears
- Open a menu in the navigation

## Proposed Solution

Setting `z-index: 1` (or higher) for the `EmailConfirmationCTA` should solve the problem.

**Note:** Interestingly, setting `position: static` for `EmailConfirmationCTA` also technically fixes the problem (I guess it does because the browser doesn't create a new stacking context in this case).

**Comment by desaijay26** [comment]
Hi @olerichter00  - can you please provide the set-up guidelines for this project,  I think the documentation has quite half-baked details. Would like to learn and contribute back to the project. Or can you please redirect me to the SPOC of this project?

**Comment by desaijay26** [comment]
Hi @dimatretyak  - I did setup the force app, Getting this error . Is there any specific configuration which requires for Relay setup..
I feel this is a path resolution issue from webpack.  Require your direction, thanks :)

```
runtime.js:39 Uncaught Error: Cannot find module '..\..\__generated__\articleRoutes_ArticleQuery.graphql'
    at webpackMissingModule (articleRoutes.tsx:83:181)
    at eval (articleRoutes.tsx:83:313)
    at ./src/Apps/Article/articleRoutes.tsx (artsy-entry-src_Apps_A.js:43:1)
    at options.factory (runtime.js:700:31)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:357:21)
    at eval (routes.tsx:8:85)
    at ./src/routes.tsx (artsy-entry-src_U.js:379:1)
    at options.factory (runtime.js:700:31)
    at __webpack_require__ (runtime.js:36:33)
```

**Comment by desaijay26** [comment]
Apart from this, I am not able to receive any data -

Error can be seen in the console. 

I think If i get auth token set correctly this should work - ARTSY_XAPP_TOKEN

Are this valid client id and secret ?

CLIENT_ID=e750db60ac506978fc70
CLIENT_SECRET=3a33d2085cbd1176153f99781bbce7c6

```
 status: 403,
      text: 'error code: 1020',
      method: 'GET',
      path: '/api/v1/xapp_token?client_id=e750db60ac506978fc70&client_secret=3a33d2085cbd1176153f99781bbce7c6'

```
